### ISSUE TITLE
BUG: Cache Not Clearing After Removal Request

### ISSUE THREAD

**Issue by zenitsu0509** [AOSSIE-Org/PictoPy#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Description:**\
The system retains cached images even after removing the cache via the interface. Old uploaded photos and folders that have been deleted still appear in the display area, causing clutter and confusion for the user.

**Steps to Reproduce:**

1.  Upload a set of images or folders.
2.  Remove the uploaded images or folders via the interface.
3.  Attempt to clear the cache using the "Remove Cache" option.
4.  Observe that previously uploaded images or folders still appear.

**Expected Behavior:**\
When the user removes images, folders, or clears the cache, the system should immediately reflect the changes and remove all cached items from the display area.

**Environment:**

-   **Operating System:** (e.g., Windows 11)
-   **Browser/Platform:** (e.g., Chrome 119)
-   **Application Version:** Commit ID: `45ebc8e5`

**Additional Context:**

-   Attached a screen recording and screenshot for reference.
-   This issue affects usability and creates confusion about the current state of the application.
- 
![Screenshot 2024-12-09 103046](https://github.com/user-attachments/assets/554d3cb9-58c1-48af-bc67-abcfdd555aef)

https://github.com/user-attachments/assets/ddbf4ef0-6024-4f6b-ae53-ac0214ea7c06

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by Jibesh10101011** [comment]
@zenitsu0509 this problem is coming because you have deleted the files from images folder but not from database , be sure if you delete files from images folder then also delete
![image](https://github.com/user-attachments/assets/8f1d454d-7271-4ecc-8121-920861124cdb)

these albums.db,faces.db,images.db,yolo_mapping.db files then these problem will not occur 

till now In this project  delete image functionality is not available so you can't delete images directly from images folder

**Comment by zenitsu0509** [comment]
Thanks bro this works for me
